            - name: Authenticate to HashiCorp Cloud Platform
  # You may pin to the exact commit or the version.
  # uses: hashicorp/hcp-auth-action@b11d0bff4bbe76283448ddca08a4a4e93c5ed4b9
  uses: hashicorp/hcp-auth-action@v0
  with:
    # The full resource name of the Workload Identity Provider, for example:
"iam/project/750ccb51-5426-4935-966a-582e8ec106e2/service-principal/cicd/workload-identity-provider/github".
This is mutually exclusive with "client_id" and "client_secret".
    workload_identity_provider: # optional
    # The value for the audience (aud) parameter in GitHub's generated OIDC
token. This value defaults to the value of "workload_identity_provider",
which is also the default value HCP expects for the audience parameter on
the token when exchanging. It should be rare for this value to be set.
    audience: # optional
    # The client ID of the service principal. This is mutually exclusive with
"workload_identity_provider".
    client_id: # optional
    # The client secret of the service principal. This is mutually exclusive with
"workload_identity_provider".
    client_secret: # optional
    # If true, the action will set the access token as an output. This is useful
for downstream steps that need to directly use the access token to
authenticate to HashiCorp Cloud Platform.
    set_access_token: # optional
    # If true, the action will export the HCP_CRED_FILE environment variable for subsequent
steps to use.

If false, the action will not export any environment variables, meaning
future steps are unlikely to be automatically authenticated to HCP and the
access token must be used directly.
    export_environment_variables: # optional, default is true
                      - name: Deploy Update
  # You may pin to the exact commit or the version.
  # uses: jfrog/connect-deploy-update@767e5a4d872e13ce1685046cff37ef9f0a3e1e03
  uses: jfrog/connect-deploy-update@v1.0.3
  with:
    # The project key (required)
    project_key: 
    # The device group names in JSON format (optional)
    groups: # optional, default is []
    # The filters in JSON format (optional)
    filters: # optional, default is []
    # The Flow UUID (required)
    flow_uuid: 
    # The Application Name (optional)
    app_name: # optional, default is 
    # The Application Version (optional)
    app_version: # optional, default is 
    # The deployment comment (optional)
    comment: # optional, default is Default comment
    # The mapping of parameters for the update configuration in JSON format (optional)
    parameters_mapping: # optional, default is {}
    # The authorization token (required)
    token: 
          
